package ru.msu.cmc.webprak.SeleniumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BuyersTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void buyers() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1050, 953));
    driver.findElement(By.id("buyersLink")).click();
    assertThat(driver.getTitle(), is("Покупатели"));
    driver.findElement(By.cssSelector(".indent")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Smith");
    driver.findElement(By.name("sortingId")).click();
    driver.findElement(By.name("sortingId")).sendKeys("Имя");
    driver.findElement(By.name("asc")).click();
    driver.findElement(By.name("asc")).sendKeys("по возрастанию");
    driver.findElement(By.cssSelector(".col > .btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) a > span")).click();
    assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("Mike Smith"));
    driver.findElement(By.id("editButton")).click();
    driver.findElement(By.id("buyerDescription")).click();
    driver.findElement(By.id("buyerDescription")).sendKeys("edited buyer");
    driver.findElement(By.id("submitButton")).click();
    driver.findElement(By.id("buyersLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) a > span")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(3)")).getText(), is("Описание: edited buyer"));
    driver.findElement(By.id("buyersLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) a > span")).click();
    driver.findElement(By.cssSelector("a:nth-child(1) > span")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText(), is("Имя покупателя: Mike Smith"));
    driver.findElement(By.id("buyersLink")).click();
    driver.findElement(By.id("addBuyerButton")).click();
    driver.findElement(By.id("buyerId")).click();
    driver.findElement(By.id("buyerId")).sendKeys("0");
    driver.findElement(By.id("buyerName")).click();
    driver.findElement(By.id("buyerName")).sendKeys("Peter Patts");
    driver.findElement(By.id("buyerDescription")).click();
    driver.findElement(By.id("buyerDescription")).sendKeys("new buyer");
    driver.findElement(By.id("submitButton")).click();
    driver.findElement(By.id("buyersLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) a > span")).click();
    assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("Peter Patts"));
    driver.findElement(By.id("deleteButton")).click();
    driver.findElement(By.id("buyersLink")).click();
  }
}
