package ru.msu.cmc.webprak.SeleniumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DeliveriesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deliveries() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1050, 953));
    driver.findElement(By.id("deliveriesLink")).click();
    driver.findElement(By.name("date1")).click();
    driver.findElement(By.name("date1")).sendKeys("0002-01-01");
    driver.findElement(By.name("date1")).sendKeys("0020-01-01");
    driver.findElement(By.name("date1")).sendKeys("0202-01-01");
    driver.findElement(By.name("date1")).sendKeys("2022-01-01");
    driver.findElement(By.name("date2")).click();
    driver.findElement(By.name("date2")).sendKeys("0002-02-02");
    driver.findElement(By.name("date2")).sendKeys("0020-02-02");
    driver.findElement(By.name("date2")).sendKeys("0202-02-02");
    driver.findElement(By.name("date2")).sendKeys("2023-02-02");
    driver.findElement(By.name("sortingId")).click();
    driver.findElement(By.name("sortingId")).sendKeys("Дата");
    driver.findElement(By.name("asc")).click();
    driver.findElement(By.name("asc")).sendKeys("по убыванию");
    driver.findElement(By.cssSelector(".col > .btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) a > span")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText(), is("Имя покупателя: Tom Smith"));
    driver.findElement(By.id("editButton")).click();
    driver.findElement(By.id("deliveryDate")).click();
    driver.findElement(By.id("deliveryDate")).sendKeys("0002-03-02");
    driver.findElement(By.id("deliveryDate")).sendKeys("0020-03-02");
    driver.findElement(By.id("deliveryDate")).sendKeys("0202-03-02");
    driver.findElement(By.id("deliveryDate")).sendKeys("2023-03-02");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.id("submitButton")).click();
    driver.findElement(By.id("deliveriesLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) a > span")).click();
    assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("2013-02-03 00:00:00.0"));
    driver.findElement(By.id("deleteButton")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) a > span")).click();
    driver.findElement(By.cssSelector("a:nth-child(1) > span")).click();
  }
}
