package ru.msu.cmc.webprak.SeleniumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GoodsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void goods() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1050, 953));
    driver.findElement(By.id("goodsLink")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("jeans");
    driver.findElement(By.cssSelector(".col > .btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) a > span")).click();
    driver.findElement(By.id("editButton")).click();
    driver.findElement(By.id("goodDescription")).click();
    driver.findElement(By.id("goodDescription")).sendKeys("edited tiny jeans");
    driver.findElement(By.id("submitButton")).click();
    driver.findElement(By.id("goodsLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) a > span")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText(), is("Описание: edited tiny jeans"));
    driver.findElement(By.id("goodsLink")).click();
    driver.findElement(By.id("addGoodButton")).click();
    driver.findElement(By.id("goodId")).click();
    driver.findElement(By.id("goodId")).sendKeys("0");
    driver.findElement(By.id("goodName")).click();
    driver.findElement(By.id("goodName")).sendKeys("cake");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.id("goodDescription")).click();
    driver.findElement(By.id("goodDescription")).sendKeys("tasty sweet");
    driver.findElement(By.id("goodType")).click();
    driver.findElement(By.id("goodType")).sendKeys("products");
    driver.findElement(By.id("goodMeasurement")).click();
    driver.findElement(By.id("goodMeasurement")).sendKeys("kg");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.id("goodTime")).click();
    driver.findElement(By.id("goodTime")).sendKeys("15");
    driver.findElement(By.id("submitButton")).click();
    driver.findElement(By.id("goodsLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) a > span")).click();
    driver.findElement(By.cssSelector(".indent:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("cake"));
    driver.findElement(By.id("deleteButton")).click();
  }
}
