package ru.msu.cmc.webprak.SeleniumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SuppliesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void supplies() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1050, 953));
    driver.findElement(By.id("suppliesLink")).click();
    driver.findElement(By.name("date1")).click();
    driver.findElement(By.name("date1")).sendKeys("0002-01-01");
    driver.findElement(By.name("date1")).sendKeys("0020-01-01");
    driver.findElement(By.name("date1")).sendKeys("0201-01-01");
    driver.findElement(By.name("date1")).sendKeys("2012-01-01");
    driver.findElement(By.name("date2")).click();
    driver.findElement(By.name("date2")).sendKeys("0002-01-01");
    driver.findElement(By.name("date2")).sendKeys("0020-01-01");
    driver.findElement(By.name("date2")).sendKeys("0201-01-01");
    driver.findElement(By.name("date2")).sendKeys("2015-01-01");
    driver.findElement(By.name("sortingId")).click();
    driver.findElement(By.name("sortingId")).sendKeys("Дата");
    driver.findElement(By.name("asc")).click();
    driver.findElement(By.name("asc")).sendKeys("по возрастанию");
    driver.findElement(By.cssSelector(".col > .btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) a > span")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(3)")).getText(), is("Комментарий: from H&M"));
    driver.findElement(By.cssSelector("a:nth-child(1) > span")).click();
    assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("jeans"));
    driver.findElement(By.id("suppliesLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(6) a > span")).click();
    driver.findElement(By.id("deleteButton")).click();
    driver.findElement(By.id("suppliesLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) a > span")).click();
    driver.findElement(By.id("editButton")).click();
    driver.findElement(By.id("supplyComment")).click();
    driver.findElement(By.id("supplyComment")).sendKeys("from H&M edited");
    driver.findElement(By.id("supplyDate")).click();
    driver.findElement(By.id("supplyDate")).click();
    driver.findElement(By.id("supplyDate")).sendKeys("0002-02-01");
    driver.findElement(By.id("supplyDate")).sendKeys("0020-02-01");
    driver.findElement(By.id("supplyDate")).sendKeys("0201-02-01");
    driver.findElement(By.id("supplyDate")).sendKeys("2013-02-01");
    driver.findElement(By.id("submitButton")).click();
    driver.findElement(By.id("suppliesLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(10) a > span")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(3)")).getText(), is("Комментарий: from H&M edited"));
  }
}
