package ru.msu.cmc.webprak.SeleniumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WarehouseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void warehouse() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1050, 953));
    driver.findElement(By.id("WarehouseLink")).click();
    driver.findElement(By.id("lookupButton")).click();
    driver.findElement(By.id("clothes")).click();
    driver.findElement(By.id("clothes")).sendKeys("5");
    driver.findElement(By.id("devices")).click();
    driver.findElement(By.id("devices")).sendKeys("3");
    driver.findElement(By.id("products")).click();
    driver.findElement(By.id("products")).sendKeys("4");
    driver.findElement(By.id("forChildren")).click();
    driver.findElement(By.id("forChildren")).sendKeys("0");
    driver.findElement(By.id("forPets")).click();
    driver.findElement(By.id("forPets")).sendKeys("0");
    driver.findElement(By.id("submitButton")).click();
    assertThat(driver.findElement(By.cssSelector(".indent:nth-child(4)")).getText(), is("Места для поставки достаточно."));
    driver.findElement(By.id("WarehouseLink")).click();
    driver.findElement(By.id("lookupButton")).click();
    driver.findElement(By.id("clothes")).click();
    driver.findElement(By.id("clothes")).sendKeys("100");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.id("devices")).click();
    driver.findElement(By.id("devices")).sendKeys("3");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.id("products")).click();
    driver.findElement(By.id("products")).sendKeys("2");
    driver.findElement(By.id("forChildren")).click();
    driver.findElement(By.id("forChildren")).sendKeys("5");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.id("forPets")).click();
    driver.findElement(By.id("forPets")).sendKeys("2");
    driver.findElement(By.id("submitButton")).click();
    assertThat(driver.findElement(By.cssSelector(".indent:nth-child(4)")).getText(), is("Места для поставки не достаточно."));
  }
}
