// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SupplySeleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void supplySelenium() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1728, 1079));
    driver.findElement(By.id("suppliesLink")).click();
    driver.findElement(By.id("addSupplyButton")).click();
    driver.findElement(By.id("supplyDateTime")).click();
    driver.findElement(By.id("supplyDateTime")).sendKeys("2023-09-20");
    driver.findElement(By.id("supplySellerName")).click();
    driver.findElement(By.id("supplySellerName")).sendKeys("Food source");
    driver.findElement(By.id("supplyProductName")).click();
    driver.findElement(By.id("supplyProductName")).sendKeys("T-Short");
    driver.findElement(By.id("supplyAmount")).click();
    driver.findElement(By.id("supplyAmount")).sendKeys("31");
    driver.findElement(By.id("supplyArrived")).click();
    driver.findElement(By.id("submitButton")).click();
    driver.findElement(By.id("suppliesLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(9) > td:nth-child(1) span")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(4)")).getText(), is("Кол-во: 31.0"));
    assertThat(driver.findElement(By.cssSelector("p:nth-child(3)")).getText(), is("Продукты в поставке: T-Short"));
    driver.findElement(By.id("editButton")).click();
    driver.findElement(By.id("supplyAmount")).click();
    driver.findElement(By.id("supplyAmount")).sendKeys("32.0");
    driver.findElement(By.id("supplyDateTime")).click();
    driver.findElement(By.id("supplyDateTime")).sendKeys("2023-09-20");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.id("submitButton")).click();
    driver.findElement(By.id("suppliesLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(9) > td:nth-child(1) span")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(4)")).getText(), is("Кол-во: 32.0"));
    driver.findElement(By.id("deleteButton")).click();
    driver.findElement(By.name("sellerName")).click();
    driver.findElement(By.name("sellerName")).sendKeys("Food source");
    driver.findElement(By.cssSelector(".col > .btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) > td:nth-child(1)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(2) > td:nth-child(1) span"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(3) > td:nth-child(1) span"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(4) > td:nth-child(1) span"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(5) > td:nth-child(1) span"));
      assert(elements.size() == 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".indent"));
      assert(elements.size() > 0);
    }
  }
}
